language: node_js
node_js:
- '0.12'
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - master
script:
- npm install -g grunt-cli
- grunt
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- sh travis_script.sh