git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
dist: trusty
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
  - development
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
- echo $AUTHENTICATION_URL
install: yarn test
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  matrix:
    secure: Cv/+GSSUbe7xmVOAnbjXzZfwaJefpT222/ZWpjkXcnHbKr7upnHocJF0KLVBUl7Rz1OsxRp8cgKxQPYDyTJPIp+AesD6dmfo8IZqSn3dK1fTCyULimW8eBCEwfl+N4FbHdc4nPDLEqy+O7O13E58rD9V3Ddrf+Fl/V2jumFkpJrKbTnZ4fogb7PUUrZXKXM/gRy07v+k6dHKSyqaTqj3ULEl9p1tczNiG4d6FX6KdmgONjXn3dKSUYYkFzoSmRzd239M+9uESmZO7W444EG4EOj2BEk9WUQRvtAjGXvruWcu0RPmd5dlztm/yLIueLzErBxgFFKzMKfvkak3Blo2eGmQzAMAZmA9g3VCe05zUuCvseLX33ZECOhFqUmQp0FmvHY9oElb+oY+QtUkU1PFki2uLBdURem6lHxCI9uSqT6K98rfj7uxXjFy+C6qEyMea3krBPNqWZ+cfF9hSc0teMJaCGe/qdKCMRjyCIfzkpKZMAKriMYbocrYkCzMMKZnthBb+J9GbLcmZ1gd71JH3yH5TfsFkmz+B3Lcq1ieLW5xGpWKx0WvjcXzdCxJGRCEzELFXrOv1kG7oEoMpu0Z0Udd5EhHmxRChEd6IMk07jXHNoj+fb14NtjrUdkip6U8X71v7hXn75rWpvkJ1QD1zmcz2fGA7QyF7jQV50KanK0=
