git:
  depth: 1
cache:
  yarn: true
  directories:
    - node_modules
matrix:
  fast_finish: true
language: node_js
sudo: required
dist: trusty
node_js:
  - stable
notifications:
  email:
  - apoorv@binary.com
branches:
  only:
  - master
  - development
before_install: 
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - yarn
  - yarn build-all
before_script:
  - jdk_switcher use oraclejdk8
install: yarn test
after_success:
  - git config --global user.email "arnab@binary.com"
  - git config --global user.name "Arnab Karmakar"
  - yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  - secure: shSOvpYF2UIC878yBGVn0J7nnHVin1f3C9EEo5laI9/381VDpyskUnkdDkO34JjE93vdfrjzModNvrkqRT+oSFjxNY95OSLyWlccEeRsWZ4tRO07RKmdj7ASLMfUaZvTm/KfjvMgo/9BrBS9taLRIJPHxebe0n3E2PjSRfLAjctAOO9uOvdTLch6We4uVPqhRz4j9v8MR+i2I3pDeUkcE+Yi15f2YtbNtaUJGE5M2YRhb5oL5zkk6i4hd6byUZBZgw4TpQEhLH5fsnxe9ujr9pAVptPL9DzzBNDLnUkTefiAMhPDUWt3THVTzV/TNgcoCE/BUCpMmnQKPHte1WS1jqNDgIYEQh94NKfuNfI/UlPhcyOIVdX/7SL7ETCus6T7cfbAlI0mMpRAnCNFThwJNN3yoRxeNxzlIaMb3IJqNEbswsWdUBPlUy3YcjQ+90jj+sr+kR30Vy8OtJeUfxNtIvOgcoMDU90BLpRvBL7rLoWrSKA1i2kkjA4k5UIvRa4mdzViI5RM/yMbx4uzqEzZ6y809OFc0nmaeA/qUhBA32QMg/Kj4yDSttBDGoSm2As4NTEFgUTH5DX4f4oQxRxK2j2ebqB0gNtfZCvTD4IQLqo9qd1bLXc29WG/EzKlLSG7iQ4xAxno768gObUKP+HVEL0cKZhg4v7ibtB7vyczLME=
  - secure: ilr31TV+buYif6no23subGZEAGHXckErx9cPCNxqlVZsMg5jIkH3mCbulixDmoIIZ0hoN+EVRafARn/QhgnZm6b4ShPofXA5r7+KSdWr2Ob2Yh8IaEwjl8GDgzFWkpbaqhx4gq5ICK/fDnetZZ8YYpER7Tz0SR4/TaJ+JfDXtUiKfKn9ZnHRdOMk64NVNjwbCDbk8c55PUGzqak86v2Yo9XqFPnw+dxKczDgnzWHiSFILbeUvMLTbRhcWqSlLXUVgdUaOWcjolbonv6c5dlvP5APW/1/t24VuYQh3vFjLOlbqaCRUo6Hku91j4ZCIf7Xy+0hHHdMxvbsavGEsC9oiGwiMqAzIkQsfu32CfA6KtMgqjhMJWGSa8FcmFVWxnYJ1c6dHyD0/Vy5XvQYPyEvl5Ciox/ZF9tvqacbqujW2+MYryNeqdz7KhpmgykCkjwG8qfjw+lIcgr7Vay5OOLOlEHZKVawcGvdOaaoICknIUB/TeTCbZ7MeEb7P29qkf8j0cM0K8KDyNAz/gePPXA596hl2zttRHa4ceSD1JIAmQH1VhlAIvDKXf2D/gXcVOGP3GY0vdnx4hZS1J6HQIQ/QnBett40M48x/ujX+Ro6f2K0Eis0j5TgUG6qrHfOZII3bFPLmzbGSuAXXN6fIShr9fW6vUIlkgljQYnHBburZAc=
  - secure: cgB4Y5+JY8fgIQbfHXvAPVgiSQzLYa6BgqunJV8ssrHt1Lzi1A918QEXOLs1h+rsc44urFSvOCmScQJBwHoz6t4FsYZ8RWBtXdJTakNc72bFQ1j86rtbHg5g9ADSUI2Vo7HX4CVg0mv3Ypqwd42FRiOb7HhUf7gCre/0wAa3z/C0X6V4PzgM4vH16+7DUPyq1FdQNfO2/6xhA/IfGqbjnEop6rzj11UU3wmB1XLnApwH19CgbQSzXsJZ43/LNUo3XBJj3U2m22R8qSUpqIPi3/yMuc0Qz/iP8rCWNwQN60WEXaz7zioWaoeA2wk92pj5TKqSg8AS8mezAkDwkSez6sX4fPMBNp4zlvNRFSgXlbDu07neID+Vbifq9yKxVLOQAgp7IQQquvJYwA7S+9/xeUUYjJ1c4o0z4BfXlt4PrDvDBsTf4ZG073DZA+jMmVSk/HbQgEKJp7lspu6aOoS07KESTWq1O1pnkADoYfzks+VzCKPfLR/AQBUHffb//5ID+Em6Q6d69gUNH3BVXVI6x9/cTxEFXUzKw11w0ZH+qfuAdjV/zh9r2TBp/M91Ysm4vAJnDZO3qbRwJEzRUK7SS+yIu6AfV6VLLma1pcR+W1IrqJUDpQzuiRrQSQ8p9iMX0MutdH4fF466LHqHj3eG2ZoGHdKAPSKcvAvjI5W1SPg=
  - secure: gf1yJ3WRKqBIvJTx/yiXEDtbeUVlEVR5nAd8F4q8bCqlEu6oDXbnNQ5M/9fj18nSPkmPQDTExpm1l2aPlu+AAZ5ydLQ98Z5jKUyTcJ40EUGOYEvVP5DxGGMFlelTEwrj7otuL4YDLuEepQkCCdgOmnv8Tau/Q0FcOkdaQ0DDEyJXZPgT38m1CHeSOsX0shZ+YxKLhjUc/Eo7O0F1HGrbLW/fP8ywUsxkpRxZxVkKZgKJuSoevZWVz2NL9xP76zYHLiAPdQtTr0VAYPFSM5Rko4UdZs606TqjLlgrBhlOqPJ4GDYG9C4WU8wLd7N2uguKKXk7t2/Rg9TInZ6v81DA0bvbx29TOx658mO1+Zpbeb+s2rTdJaASWkHrw7mfPIE8+/Hmc2KQwIUoUf4fAScVqIe6OW/nIod65JSBxOqzUwpf4l2Z9mqfFckR9pnLhom6WfzpFZn8rvWJ4XQPu9wJSM82pDpcSKF3IkdbUVMGj8tCts9TtCSM1+WiNtOoOtyKccjJpIqtO/6IOYAg0HT1tqeUn6LfzstIOQj3AG/Y6HZprH8OIwhjIB2kigMGtLCVYElCWyOE9ZAnyQLYu+wZCET1VJuQHkB9trPdGQ/rZJOOy7wtgyUXbIq4aEEiU3eDsKge+ncCtZoBxXD0BXYO9KWJMI8o8XkIrSRIKjlO+SQ=
#notifications:
    #slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS