git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
dist: trusty
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
  - development
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
- echo $AUTHENTICATION_URL
install: yarn test
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  - secure: bH3GHTC9yDHkoHoE2OOImiveiCa2tv+6Y55u5ntdqbC/CpAGZugE8UYOAQdDM9zjSKsIx2q2HdnSPWrggS4YsTzA7XY/YG7o2fbmrQEncusZY0KPFZ7NDDW4/ybI3E13qcahWvwZaVPOxhsR8PMWAWzEEDUOzrj8nNKChjjfBQwViBrpHfV8aNqPsjSj9jAK3vSspa0Ah/PCq8mTAjja4Kte+azOA9yv3tlQ2icrSvTWl42oxD1E7Kk2avT4jpu/p1ETUDtP/wjifJzH92F44qoJ15Kpm1hqAX6GqaVQTOWq4FkzBWBnJoATGFAxCg6C8XSdHAuWF6cj7CF0xW+te2gyOMGFJ6C7URag6QG3Yo3dggRa+cYbWmAVNplI2RiACQDrxr7J77XE5+7dG0el3uLtNrM+KLaaHgp68/7At7XLlS/Klov5IOD5JDGXocfKMcNOyIJeSVcxMQH4MiMQqqZ3AdJc5z0cAwPNBm3dFRomG7a94KVuKNIcnHqBkGc/PtQp7Yg7tZfmyHSm6eawytmgACa93SPc8LUU3sbpfVe/fneteO3iq0I94G88pq8MXVAKWWBIBsjouriglOMbhg8jWZk6cpv3ShnfGOk4Fbcl2nwDQvTEx6kT0BPHTYwBGG+eq12MGsaPMyGvOFMMfzDPwZGZnKnVURIUhOJo15E=
