git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
dist: trusty
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
  - development
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
install: yarn test
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  - secure: i21zfrGG4H7INaPAdUJ/NkRdEuhFt2xvs7NI8rEBI9JJiX45gJJCscDnkbe2qcFzh5JT7TV5gfZUykvJyg3hkXojwNY4vyDJ1H9lYwZLTGTWr9PGKTQyMOc1enKZQAUl15qaZ7n0EomcfDm0yM+VJPBpLdlxIV5rvw7AY4bgw8EvFEkuLAZsEfk6eOzTqdYpqqLsyQW2bYOtdza9GLarFOsdnGYFfdnQTLcL7Pc0tEPalZeM5H3qwFxAULagIBVZtTWgMzW59Z1EfHDFgJHd+FXjJf7845yNXOqXpKz2crHRljG6lp529nzeC1OqLy5S/egjvu3pDQ49OGLafAK72b22gpvUqPfhG+4EyDZpuAYOoKryVa0r5UY7vYhhs22ZXOtUhP/h9Fpkjl25Delex3kERy8hOuUL6ZsZQbAHfz/gynVehwlAG7uaChd+O0p1KWPbarQRFG6ii7AzhTAZVTCH2wjJatm7fV20Dwzs5V1O0ycty+vhdUuMVLeGGRSpIrDOzgGD3Pd5qTTNJM2EK6lwL70pX12hdCNtnuaLu0hdEmxWosu1vAT/kmZgJeEE7RMQPdigVxi6LfxnWG9ySKDjJ2amJHZQt2w1iaRt6H038rfiewm+pWPJ2gXk+gJbAD5ZROB7wzj/3objDv2T5/YOqsZ0cSR6WEACl2fASFg=
