git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
dist: trusty
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
  - development
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
install: yarn test
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  - secure: l4qKoRu0/vfgCFVqqM7paMpdecrp9iZjMIRmwM2LZ/2ggLTCtk2Ci1IVHKNRKELAJZk6ZDSoR4fQ0/SmoiqFSud8hLHubzuMfrPCn4LKIDkBwJ4DxypcC4heYK7QrRIM7c9QnMT1BhMkJG46os3ve87QpgOrf0b7UL7BuM0xGLTmQRGOMUSQ2LXJaUhH+4qsU1c5bSL/86O2BiuX0uDWsAXPPrMgGxpVbjIzBCXkKtvpWcfSncWtOJkyCpk6mm0agEd7IrD9IuuZV/SwyaQ4PEzjPoakGR8f5tigd0XMEAaE2ePhPZ58HC3O7B4v+fXYnhiAsM9BlLTWj0IFi53vvdUcUIMS6712w5JIgA+cMg4H876qosiGZ6xozlDZ/cfwY5hbZQFe4She0ToGDQefC+1VQB33KRnxPxcUb+Bg6+EW94ydxli/GkmSosayr1b2e/6EGu/04cdQ23rOv+My8i+3py5+U5kq1Opi/YNcnZ0uhMeUPdduLwfkbbPcejkJDF1thCKnBRroObLHLSi8FXMTN+Ig4mtpdJa4nvgMRGTbxsFFsPOn4lIEZj5Iv4Xv3dYCpyoUpYNu46At8+f2Q0DmXXz3RTNBmdliygm52RQfFBViUT1hrtQ2OsRsVo1irJbCGRYH8IDV99LxX5YttqfYlwLCc/tWksVX7CwM/V0=
