git:
 depth: 1
cache: yarn
matrix:
  fast_finish: true
language: node_js
node_js:
  - "6"
addons:
  browserstack:
    username: 'jeanyvessireau1'
    access_key:
      secure: "r6j+AREzj151bb8GPnM5sm3cjxCLB+9axUsul0twvGrOIeeE/c3fX3PfigfATVbiIXuu8CkxAkzbYFIfuTgjw++TXu4eaV7NssA/p9LOvI/4J1dgSveRZke+ljRFqdyPsFyg+5hIoTUwITsQQ9jVOd6ExapBWvoWEGdtrFuU3+i/h1k/SzY3MnFWLWlhouky6n8DqhvpVB9T2Rpv1cgklVVcpLXoEFT5Zuav5CHFHnI/1c3UYUcrQGi9cJ6lBEpkdmZtIEVns3Vkmop5SqRhE2dMz+53yU86O4vFDEBaFPODwJoR/O6Ye2urYm1Xt7XJ00YD0eyEOjZaQvQsAg9sp4Zsffae05Bxpibm+VMLq8hsuA9zQef88sJQ8weY5r+KvqvAJPPIh4Pulvz83B/3l7301TbC/GOzOpQx2igDSdmb45l7eeRWjVymX8yqe1xgei/OCKMbujLm60BTQrpH3YEjEf93+cSOap5ybgtetQiK/o6CPhFV/9f1lLWmOKfWFXoPieXQabnjBrjdIrOGM9ZhCD5ocjVT1cLvMo6cYx9hVfyEkb/FiziwzrH8BWYJuF8gjpXM6iKqq0Kjc9Q8AEAUUEJZDG5bmyHg2xSSv29gGL75jaIED1ZhNDL71wBaQpzMPZRKk8X2eHYBKPBl+wSS63g5uKVBvrWPVWkBuMQ="
notifications:
  email:
    - arnab@binary.com
branches:
  only:
    - master
    - development
script:
  - yarn test-browserstack
  - git config --global user.email "arnab@binary.com"
  - git config --global user.name "Arnab Karmakar"
  - yarn deploy-gh-pages
env:
  global:
    secure: BA4dVZcwJrk0GhUaUcQreHR+xXlvtVEILelPXU/6+FSIe3l/JQWS09r+0NDMDvRr4BIj3MuAte7FGiTzTRvKDi2GKBHYhE7Z8tnBKmm24masTACPC2lht5XnpEatil5b7rwGWv0JrsBE3qSl0GK94X7H5lVLgshhMepg4NhK2hx7tk/17weDXgwXC/J4rzq7de9377LYhmJka2WphD8xUDIYkTSn5PuDGrLZ2gzCn6e13vcd4nn3ZIbTJkyMg2dsxZiVJ+ISagdeZ1DJ5lmnl6l+kH9c/vLfQ8h72AKkLVBn2RmR7Bv9IUDnUV5lhAekRZ9umUKp5paxXrR3thpPfztQoLqETPURqoqOhltxxVFp0N7KjKMJkZGs+eExUmoX4U1T3oe9t8fjA41bLrIJz+dF2v0afxI+fxRZc2O29IHeaFP2FVdY8SEHp+UH3dY89pU3zTo1UyCmalhCDDA8hR5VIq+HdvTTXEUceIegGue/YIr4lRZv98gMx6iSsiOTFHbPLz8N+eBbKEVRLPfIkJX8QWlBFn7r0iuFuBfCUKyvZM9KzH3gKpeQ2VcCTnLqTBM8GiWusv1icHxHQMIX0mKrvdFqkL7bH/RY6GT+7vTsyG7ZumzCS/6DOlaTaiyDAAVx5dJQtd9NAH5MgOrvOX1Z/eRO0kaATyC8Lh/8LIo=
