git:
  depth: 1
cache: yarn
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - master
  - development
script:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: G8mqpu5XaXLyiusAOlsLLFX52aq1/d5BB/enPLL4PzYJ6A/toFxxP/Az5JJdz+0JwkQQEbGSETvQt+sZyzIdMuwu9Lj/LxQP02RUvTkc0ZzfwhHn5iBFMrUsv1K+iynzzedk0jiDWBPorT/L7dq18LbYWB9AM0pZwKjcktvkvJatMjgFft7818+qi+UjRvrL/sRkXDRisS/UEQP7+42F2avUWLcoLfFir0lLLLhyJXPhSL9/ifzAneTaGm89HEfgKVQj4/qp6NSfgQsr89RHp2xAzoGQRkB1ZL45QrQPbxDIkICdqVz43kOnjb/EdaZmolimqHKEyHpCIbZSK0z0DVBv8nW2gHpsSOmOdnFTzt5b9u0wToLbUnWapIbrlzJ4O3aetSpmNh0sKp2LWCCRN8jaClTWjyiTNHC3Az7nETeygrvXP4rID5n2/BvUQWYUpgOS3WqYxL9KhhMl2kS2W+PkJZA4EYdt+JOkd5ogIGP6Jl0rSZehg8LWX1h77fY6Kq560fKSzq9yUw1kHYtbcc5debXbAkHzQ6A5gnGHg6wjPub7IOieOXFKrrCc7gSsbkF3W/KM56ko+ZSBbm1iHxxMnItWw8MkcudRMsGS/3n3hwn3W79rUDBfw028IfyRGhF14Bousw7mMYflj3/KvMcyUxAW/j0bzE9xbiN0lcc=
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
