git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
matrix:
  fast_finish: true
language: node_js
node_js:
- '7'
dist: trusty
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
  - development
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
- echo $AUTHENTICATION_URL
install:
  - yarn build-all
  - yarn test
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  - secure: j1hmmCQHgKcKRm9eckq6BcycasuF7BA07TyBc3N5vkVVsPccFIFjP9CTFs91JBvjccq7kaySq81G+XGnaVe+YJ67JQaefoBehrPuCVkLTODk+WQ9ic4VH19KMWxYdTSn1KVdlJjiW8Dc4DBYmjMTonRjmdusZgE1Od3EP2qrSgUbDs7+QV/P/CUTZoQCacYeXvDgPzNULOsHFP8FPUGjPWXxQCvphg8b4tvxnIiLGD4CNYCOKRA3pkF10ct6ZLXsU7iJQdbKHqKvi55oZ3Iab8leb7UFAGnuzX8yt1NeIrPHl9iKLMEGYmEUvv55+GBbjmbcZmgDw600F4D2Z7LEqoj+khg8rwPp0kWXnvSiAvZs+aGESoL4pEyvQRRSiSW+X/sVL6Bb/XoiWYcgxPW+eBTqo7zbD7Up/+dKSXudkwABFqoaD7kfoEJWzh2qE8tvm6tz8R2Te3g7STNcz5QJshH1EFMjGbBLh/cgIn17nYmaDUAq68fr+IOFdOIlZP2rjyCHGnEegBMiEq7RQkzktydchNlbUbK9elimJ9yO6hBrFwDHAuwujmMWyPRmz0NSol1GAonbUIHTqHTnlhNbKZBYY299ViBPXqXBAi40k3jfwH2xUlPPXvbR/E3GFPgF8v5s56r/DUTvV9fCAqZRo9RbiEfZKo6pZYPXJWtCrNM=
